<a href="https://colab.research.google.com/github/mayvelardez95/ypf_ingenias_datascience/blob/main/Notebook_5_primera_entrega_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
 # 1.Crear un arreglo de ceros de longitud 12
import numpy as np
array = np.zeros(12)
print(np.zeros(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 2.Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array1 = np.zeros(10)
array1[4] = 10
array1

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
# 3.Crear un arreglo que tenga los números del 10 al 49
array2 = np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 4.Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array3 = np.arange(9). reshape(3,3)
array3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 5.Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array4 = np.random.randint(0,100,100)
# array4.size
# array4.mean()
# array4.var()

714.6370999999999

In [ ]:
# 6. Calcular la media de un arreglo usando np.sum
np.sum(array4)
# np.sum(array4)/ len(array4)
np.sum(array4)/array4.size

49.77

In [ ]:
# 7. Calcular la varianza de un arreglo usando np.sum y np.mean
suma_de_cuadrados = np.sum((array4 - np.mean(array4))**2)
varianza = suma_de_cuadrados/array4.size
varianza

714.6370999999999

In [ ]:
# 8. Crear un array de números aleatorios usando np.random.randn
array5 = np.random.randn(10)
array5

array([-1.75728971, -0.57708501,  0.33630167,  1.80072437,  0.37602689,
        1.42209869, -0.50080327, -0.57486105, -0.25869055, -0.53483711])